package Week1.Day3_1006.CollectionPractice.Map;

public class AddressList {
    private String[] addressList = {
            "https://github.com/dongyeon-0822/java-project-exercise", "https://github.com/kang-subin/Java", "https://github.com/KoKwanwun/LikeLion.git", "https://github.com/lcomment/Algorithm_Solution--Java/tree/main/LikeLion", "https://github.com/cmkxak/likelion-java-course", "https://github.com/rnrudejr9/CodeLion-git-test", "https://github.com/Qkite/java-excercise-01/tree/main/src", "https://github.com/lucyoz/java-exercise", "https://github.com/percyfrank/like-lion", "https://github.com/KimGunWoo9595/Lion_Java_Pratice", "https://github.com/KimKiheon/LikeLion", "https://github.com/kny3037/java-exercise", "https://github.com/KimDohyoun79/remote_Lion.git", "https://github.com/kimkimj/create-repo1", "https://github.com/mingry2/intellij-git-exercise1", "https://github.com/Min-ji99/intelliJ-git-exercies", "https://github.com/sangho527/Like_Lion_Java", "https://github.com/ReadnThink/Like_lion.git", "https://github.com/yejinstar/git_exercise_push", "https://github.com/dmdwns2/java-git-init", "https://github.com/Geuun/Java_Algorithm", "https://github.com/O-sulloc/java-exercise-1005", "https://github.com/chordpli/likelion_course", "https://github.com/strongcookdas/java.git", "https://github.com/Kim-Ji-Yeong/Java-exercise", "https://github.com/k0605ja/git-test", "https://github.com/pigeon2gugu/like-lion-2/tree/main/src/class_221005", "https://github.com/hj-k66/git_exercise_2", "https://github.com/moomineee/JavaEx", "https://github.com/sujin-park0607/java-project-exercise", "https://github.com/joypeb/java-project-push-test", "https://github.com/pi22-a/git_practice.git", "https://github.com/JemJem70/Algolism/tree/master/src", "https://github.com/BearCrying/Git_Excercise/tree/main/src", "https://github.com/Bae-Ji-Won/Java-Study", "https://github.com/geunnseung/java_exercise_intellij_push.git", "https://github.com/JiMandy00/Java_LikeLion", "JAVA-GIT-TEST/src at main · seop93/JAVA-GIT-TEST (github.com)", "https://github.com/sjhlko/git-exercise-java", "https://github.com/tgseo76/javja-ex", "https://github.com/seanee3670/CodeLion/tree/master/src", "https://github.com/dalddu/Intellig-git-exercise", "https://github.com/hyunsik96/git-exercise-java-push", "https://github.com/ccodding/git-exercise-java-push", "https://github.com/TaylorSwiftlove/git-exercise-java", "https://github.com/jinwoooooo/git-exercise-java-push", "https://github.com/simhyunbo/git-exercise-04.git", "https://github.com/ahngiwon00/git-exercise-java-push", "https://github.com/ahn-ji0/java_exercise", "https://github.com/Changbum97/like-lion-java", "https://github.com/SoonMinEom/LikeALion", "https://github.com/ohy1023/newtest", "https://github.com/SuInWoo/LikeLion2th",
"https://github.com/inkyu-yoon/IntelliJ_Commit_Test", "https://github.com/KaNoopy/like_lion.git", "https://github.com/ondayary/java-init-project.git", "https://github.com/dohyunre702/codelion_intelliJ", "https://github.com/leejoonsang/bes2", "https://github.com/naegonggae/lion", "https://github.com/Soyeong4250/IntelliJPush", "https://github.com/slrkajsep337/JavaStudy", "https://github.com/ajin0516/java_project.git", "https://github.com/yjyj1023/java-Calculator2",
"https://github.com/hyeonju01/likelion_repo3_test/tree/main/src/week3/day2", "https://github.com/hakjun1/intelij-git-exercise03", "https://github.com/jangseoyun/Intellij-git-exercise", "https://github.com/Senna97/Like-Lion", "https://github.com/zinxeon/git-exercise-push", "https://github.com/su0545/like-lion-java.git", "https://github.com/Nickolodeon98/second-java-exercise", "https://github.com/daehwan0307/JAVA_Study", "https://github.com/sanghee2359?tab=repositories", "https://github.com/wogus0518/LikeLion-Backend", "https://github.com/heejunns/git_exercise_push.git", "https://github.com/h5000n/git-java-ex211005", "https://github.com/mooonju/java-exercise", "https://github.com/coastby/java-project", "https://github.com/Yunjaejo/new-project-push-test", "https://github.com/Combi153/BackEndSchool2", "https://github.com/chlalswns200/java_push", "https://github.com/S2uJeong/git-exercise-java", "https://github.com/gemdoq/exercise", "https://github.com/surpmh/intellij-git-exercise", "https://github.com/sandee-han/java-project-push-exercise", "https://github.com/JinDDung2/java-project/tree/main", "https://github.com/menuhwang/LikeLion", "https://github.com/cvivis/git_practice2022/tree/main", "https://github.com/lay423/java-project",
    };

    public String[] get() {
        return addressList;
    }
}
